services:
  backend:
    build:
      context: ./
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    command: ["serve"]
    restart: always
